
import "./globals.css";
import { Inter, Lexend_Deca, Outfit,Capriola } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  weight: "400",
});
const capriola = Capriola({
  subsets: ["latin"],
  variable: "--font-capriola",
  weight: "400",
});
const lexend_deca = Lexend_Deca({
  subsets: ["latin"],
  variable: "--font-lexend_deca",
  weight: "700",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2495784574263932"></script>
      </head>
      <body
        className={`
        ${outfit.variable} 
        ${inter.className} 
        ${lexend_deca.variable}
        ${capriola.variable}
        `}
      >
        {children}
      </body>
    </html>
  );
}
